# Generated by Django 3.1.3 on 2021-01-12 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('begin_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('country_codes', models.CharField(blank=True, max_length=2048)),
                ('cities', models.CharField(blank=True, max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPosition',
            fields=[
                ('coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.coordinates')),
                ('name', models.CharField(max_length=256)),
                ('type', models.SmallIntegerField()),
                ('rating', models.SmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('main_image', models.CharField(blank=True, max_length=256)),
                ('pictures', models.CharField(blank=True, max_length=4096)),
                ('country_code', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.travel')),
            ],
        ),
    ]
