# Generated by Django 3.1.3 on 2021-01-13 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coordinates_travel_travelposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelposition',
            name='id',
            field=models.AutoField(auto_created=True, default=-100, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelposition',
            name='coordinates',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.coordinates'),
        ),
    ]
