# Generated by Django 3.1.5 on 2021-01-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210116_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
