# Generated by Django 3.1.3 on 2021-01-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_friends'),
        ('api', '0006_auto_20210128_2312'),
    ]

    operations = [
    ]
