# Generated by Django 3.1.3 on 2021-01-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20210129_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelposition',
            name='main_image',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
