version: "3"

services:     
  traweb-api:
    container_name: traweb-api
    build: traweb_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./traweb_api:/code
    ports:
      - "8000:8000"
  storage:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "10000:10000"
      - "10001:10001"